[build]
builder = "NIXPACKS"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs_20", "python3", "python3Packages.setuptools"]

[deploy]
startCommand = "node server/index.js"
healthcheckPath = "/api/health"
